### ISSUE TITLE
cannot find 1.0-SNAPSHOT version

### ISSUE THREAD

**Issue by cputoaster** [GoogleCloudPlatform/cloud-trace-java-instrumentation#20]
there seems to be a 0.1.0 version in maven central, and a 0.1.1-SNAPSHOT being referenced in the example

**Comment by cputoaster** [comment]
just to be clear, 0.1.0 seems to work, but the documentation / examples / reality don't match

**Comment by ubschmidt** [comment]
Thanks for reporting this issue and apologies for the delay.

Fixed in https://github.com/GoogleCloudPlatform/cloud-trace-java-instrumentation/commit/6ca379383d6710cfaa10408638d50b8bee0e7f27#diff-84beffd3a0d49636a58ce6080caa87c7.
