### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ubschmidt2** [GoogleCloudPlatform/cloud-trace-java-instrumentation#28]
We need to release a new version which includes https://github.com/GoogleCloudPlatform/cloud-trace-java-instrumentation/pull/24.

**Comment by cputoaster** [comment]
Sorry to bother again, but is there anything planned here? Or should I just try to somehow build it myself without a clear version from github?

**Comment by mtwo** [comment]
Talked to @bogdandrutu and he's going to push a new version once he gets back to the office. ETA is this Friday or the following Wednesday.

**Comment by cputoaster** [comment]
Not trying to be too pushy, but...

**Comment by bogdandrutu** [comment]
Version 0.1.1 should be available now.
